version: "3.9"

services:
  restart: unless-stopped

  client:
  container_name: movie-app
  build: ./
  ports:
    - "3000:3000"
  networks:
    - client-net

networks:
  client-net:
    driver: bridge
